# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files first to install dependencies
COPY package.json package-lock.json ./

# Install dependencies without running any scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Set the entrypoint
CMD ["node", "dist/index.js"]
